# SPDX-FileCopyrightText: 2025 Lukas Pieper
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Assemble Debug workflow

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Assemble Debug
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Setup
      uses: ./.github/actions/setup

    - name: Assemble Debug
      run: ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: APK
        path: androidApp/build/outputs/apk/debug/*.apk
