# SPDX-FileCopyrightText: 2022 Lukas Pieper
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: continuous

on:
  push:
    branches-ignore:
      - 'dependabot/**'
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  detekt:
    uses: ./.github/workflows/lint-detekt.yml
    permissions:
      security-events: write

  lint:
    uses: ./.github/workflows/lint.yml
    permissions:
      security-events: write

  build:
    uses: ./.github/workflows/assembleDebug.yml

  jvmtests:
    uses: ./.github/workflows/tests-jvm.yml

  licensing:
    name: Run License Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Lint licensing
        uses: fsfe/reuse-action@676e2d560c9a403aa252096d99fcab3e1132b0f5 # v6.0.0

  fastlane-validate:
    name: Validate fastlane metadata
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      
      - name: Validate fastlane metadata
        uses: ashutoshgngwr/validate-fastlane-supply-metadata@c8857fdbbd3e00f9a5cbe8604bcecfa95ce8fef8 # v2.1.0
